---
ipaddr: "{{ansible_eth0.ipv4.address}}"
zookeeper_hostnames: "{{zookeeper_hosts|map(attribute='address')|join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port }}"
public_network: 172.31.0.0/16