---

logstash_version: "2.2"
logstash_defaults: |
  LS_USER=root
  LS_HEAP_SIZE="256m"

logstash_inputs: |
  beats {
    port => 5044
  }
  file {
    path => "/var/mesos/slaves/*/frameworks/*/executors/*/runs/latest/stderr"
    close_older => 30
  }
  file {
    path => "/var/mesos/slaves/*/frameworks/*/executors/*/runs/latest/stdout"
    close_older => 30
  }
  file {
    path => "/var/log/mesos/mesos-slave.INFO"
  }
  file {
    path => "/var/log/mesos/mesos-slave.WARNING"
  }
  file {
    path => "/var/log/mesos/mesos-slave.ERROR"
  }

logstash_filters: |
  grok { match => ["path","/%{GREEDYDATA}/executors/%{GREEDYDATA:app}[.]%{GREEDYDATA}"] }

  if [app] !~ ".+" {
    mutate {
      replace => ["app", "default"]
    }
  }

logstash_outputs: |
  if [@metadata][beat] == "topbeat" {
      elasticsearch {
        hosts => "elasticsearch.service.consul:9200"
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
        template => "/etc/logstash/template.json"
        template_overwrite => false
      }
  } else {
      elasticsearch {
        hosts => "elasticsearch.service.consul:9200"
        template => "/etc/logstash/template.json"
        template_overwrite => false
      }
  }

defaults_RedHat_plugin: "/opt/logstash/bin/plugin"
defaults_Debian_plugin: "/opt/logstash/bin/plugin"
logstash_tmpl_dir: "/etc/logstash/"


