---
# - name: Install packages
#   apt: name={{item}} state=installed update_cache=yes
#   with_items:
#     - git-core
#     - librados-dev
#     - librbd-dev
#     - gcc

- name: Install plugin
  copy: src=rbd-docker-plugin dest=/usr/local/bin/ mode=755

- file:
    path: /etc/init/rbd-docker-plugin.conf
    state: absent

- name: generate systemd unit file
  become: true
  template:
    src: "rbd-docker-plugin.service.j2"
    dest: /etc/systemd/system/rbd-docker-plugin.service
    owner: "root"
    group: "root"
    mode: "0644"

- command: /bin/true
  notify:
      - stop docker

- command: /bin/true
  notify:
    - restarted rbd docker plugin

- command: /bin/true
  notify:
      - start docker
