---
- hosts:
  - mesos-master
  - marathon
  - zookeeper
  gather_facts: false
  tags:
    - always
  tasks:
    - name: check for python2
      stat:
        path: /usr/bin/python
      ignore_errors: yes
      register: systempython2
    - name: install python2 for Debian based systems
      raw: sudo apt-get -y install python-simplejson
#      ignore_errors: yes
#      when: systempython2.stat.exists is undefined or systempython2.stat.exists == false
    # Try to install python2 on Fedora > 23
    - name: install python2 for Fedora
      raw: sudo dnf -y install python creates=/usr/bin/python
      ignore_errors: yes
      when: systempython2.stat.exists is undefined or systempython2.stat.exists == false
    - name: gathering facts
      setup:
    - name: install required packages for Fedora > 23
      raw: sudo dnf -y install python2-dnf libselinux-python ntp
      when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 23

    - name: check if it is Atomic host
      stat: path=/run/ostree-booted
      register: stat_ostree

    - name: set fact for using Atomic host
      set_fact:
        is_atomic: "{{ stat_ostree.stat.exists }}"

- hosts: zookeeper
  sudo: yes
  roles:
    - ansible-java8
    - ansible-zookeeper

- hosts: mesos-master
  sudo: yes
  roles:
    - role: ansible-common
    - role: ansible-docker
      docker_pkg_name: docker-engine=1.12.6-0~ubuntu-xenial
      docker_opts: "--ip={{ipaddr}} --dns={{ipaddr}} --insecure-registry 10.0.0.0/8 --insecure-registry 172.16.0.0/12 --insecure-registry 192.168.0.0/16 --insecure-registry registry.service.consul:31500"
    - role: ansible-mesos

- hosts: marathon
  sudo: yes
  roles:
    - role: ansible-marathon
