---
- hosts:
  - mons
  - osds
  - mesos-slave
  gather_facts: false
  tags:
    - always
  tasks:
    # If we can't get python2 installed before any module is used we will fail
    # so just try what we can to get it installed
    - name: check for python2
      stat:
        path: /usr/bin/python
      ignore_errors: yes
      register: systempython2
    - name: install python2 for Debian based systems
      raw: sudo apt-get -y install python-simplejson
#      ignore_errors: yes
#      when: systempython2.stat.exists is undefined or systempython2.stat.exists == false
    # Try to install python2 on Fedora > 23
    - name: install python2 for Fedora
      raw: sudo dnf -y install python creates=/usr/bin/python
      ignore_errors: yes
      when: systempython2.stat.exists is undefined or systempython2.stat.exists == false
    - name: gathering facts
      setup:
    - name: install required packages for Fedora > 23
      raw: sudo dnf -y install python2-dnf libselinux-python ntp
      when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 23

    - name: check if it is Atomic host
      stat: path=/run/ostree-booted
      register: stat_ostree

    - name: set fact for using Atomic host
      set_fact:
        is_atomic: "{{ stat_ostree.stat.exists }}"

- hosts: mons # gather mon facts first before we process ceph-mon serially
  tasks: []

- hosts: mons
  become: True
  serial: 1 # MUST be '1' WHEN DEPLOYING MONITORS ON DOCKER CONTAINERS
  roles:
    - role: ceph-mon
      mon_containerized_deployment: false
      bootstrap_dirs_owner: 64045
      bootstrap_dirs_group: 64045
      monitor_name: "{{ ansible_hostname }}"

- hosts: mons
  become: True
  roles:
    - role: ceph-fetch-keys
      mon_containerized_deployment: false

- hosts: mesos-slave
  become: True
  roles:
    - role: ansible-docker
    - role: ceph-client
    - role: ansible-rbd-docker-driver
