- src: https://github.com/tw-cde/ansible-zookeeper.git

- src: https://github.com/tw-cde/ansible-java8.git

- src: https://github.com/tw-cde/ansible-docker.git

- src: https://github.com/tw-cde/ansible-mesos.git

- src: https://github.com/tw-cde/ansible-marathon.git

- src: https://github.com/tw-cde/ansible-elasticsearch.git

- src: https://github.com/ceph/ansible-ceph-mon.git

- src: https://github.com/ceph/ansible-ceph-osd.git

- src: https://github.com/ceph/ansible-ceph-client.git

- src: https://github.com/ceph/ansible-ceph-fetch-keys.git