---

- name: restarted rbd docker plugin
  service: name=rbd-docker-plugin state=restarted enabled=True

- name: stop docker
  service: name=docker state=stopped

- name: start docker
  service: name=docker state=started
